### ISSUE TITLE
Reading consensus_pwms.meme into python

### ISSUE THREAD

**Issue by vitkl** [jvierstra/motif-clustering#4]
Hi @jvierstra 

Thanks for an amazing resource. How do you recommend reading the consensus PWM file into python? Ultimately, I need a dictionary with PWMs: {motif_name: np.ndarray}.

I tried using https://biopython.org/docs/1.74/api/Bio.motifs.meme.html but it complained about the file format.

**Comment by jvierstra** [comment]
See this script in the `bin` directory: https://github.com/jvierstra/motif-clustering/blob/master/bin/meme2jaspar.py

It will convert MEME to PFM matrices.

**Comment by vitkl** [comment]
Fantastic, thank you!
